#!/bin/bash

# ==============================================================================
# This script analyzes the current directory structure and file contents to
# generate a self-contained 'setup_project.sh' script.
#
# The generated script can then be run on any system to recreate the project
# structure and files, making it a portable template.
#
# It ignores common version control and build files.
# ==============================================================================

# Exit immediately if a command exits with a non-zero status.
set -e

OUTPUT_SCRIPT="setup_project.sh"
PROJECT_ROOT_DIR=$(pwd)
CURRENT_SCRIPT_NAME=$(basename "$0")

# Define patterns to ignore.
# These will be excluded from the generated script.
IGNORE_PATTERNS=(
    ".git"
    ".github"
    ".gitignore"
    ".dockerignore"
    "LICENSE"
    ".sgt"
    "__pycache__"
    "*.pyc"
    "*.log"
    "$OUTPUT_SCRIPT"
    "$CURRENT_SCRIPT_NAME"
)

# Create the output script and add the header.
echo "Creating the new '$OUTPUT_SCRIPT'..."
cat << 'EOF' > "$OUTPUT_SCRIPT"
#!/bin/bash

# ==============================================================================
# This is a self-contained script that recreates a complete project structure
# including all files and their contents.
#
# This script was automatically generated by 'setup_project_script_maker.sh'.
#
# Usage:
#   1. Make this script executable: chmod +x setup_project.sh
#   2. Run it: ./setup_project.sh
# ==============================================================================

# Exit immediately if a command exits with a non-zero status.
set -e

PROJECT_NAME="my_project"

echo "Creating the project structure for '$PROJECT_NAME'..."
mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

echo "Creating directories..."

EOF

# Function to check if a path should be ignored.
should_ignore() {
    local path="$1"
    for pattern in "${IGNORE_PATTERNS[@]}"; do
        if [[ "$path" == *"$pattern"* ]]; then
            return 0 # True (should ignore)
        fi
    done
    return 1 # False (do not ignore)
}

# Recursively find all directories and files.
find "$PROJECT_ROOT_DIR" -print0 | while IFS= read -r -d '' item; do
    relative_path="${item#$PROJECT_ROOT_DIR/}"

    # Skip the root directory itself.
    if [ "$relative_path" == "" ]; then
        continue
    fi
    
    # Check if the path or any of its parent directories should be ignored.
    if should_ignore "$relative_path"; then
        continue
    fi

    if [ -d "$item" ]; then
        # It's a directory, add a mkdir command.
        echo "mkdir -p \"$relative_path\"" >> "$OUTPUT_SCRIPT"
    elif [ -f "$item" ]; then
        # It's a file, add a here-document to write its content.
        echo "" >> "$OUTPUT_SCRIPT"
        echo "echo \"Creating file: $relative_path\"" >> "$OUTPUT_SCRIPT"
        echo "cat << 'EOF' > \"$relative_path\"" >> "$OUTPUT_SCRIPT"
        cat "$item" >> "$OUTPUT_SCRIPT"
        # FIX: ensure EOF is always on its own line
        printf '\nEOF\n' >> "$OUTPUT_SCRIPT"
    fi
done

# Add a final success message to the generated script.
cat << 'EOF' >> "$OUTPUT_SCRIPT"

echo "----------------------------------------------------"
echo "Project '$PROJECT_NAME' has been successfully created."
echo "You can now navigate into the new directory: cd '$PROJECT_NAME'"
echo "----------------------------------------------------"

EOF

# Make the generated script executable.
chmod +x "$OUTPUT_SCRIPT"
echo "The script '$OUTPUT_SCRIPT' has been created and is ready to use."
