#!/bin/bash

# ==============================================================================
# This script analyzes the current directory structure and file contents to
# generate a self-contained 'setup_project.sh' script.
#
# The generated script can then be run on any system to recreate the project
# structure and files, making it a portable template.
#
# It ignores common version control and build files.
# ==============================================================================

set -e

OUTPUT_SCRIPT="setup_project.sh"
PROJECT_ROOT_DIR=$(pwd)
CURRENT_SCRIPT_NAME=$(basename "$0")

# Patterns to ignore (exact match or glob)
IGNORE_PATTERNS=(
    ".git"
    ".github"
    ".gitignore"
    ".dockerignore"
    "$OUTPUT_SCRIPT"
    "$CURRENT_SCRIPT_NAME"
    "*.pyc"
    "__pycache__"
    "*.log"
)

# Check if path should be ignored
should_ignore() {
    local path="$1"
    for pattern in "${IGNORE_PATTERNS[@]}"; do
        if [[ "$path" == $pattern || "$path" == *"/$pattern" || "$path" == $pattern/* ]]; then
            return 0 # ignore
        fi
    done
    return 1 # keep
}

# Create output script with header
echo "Creating the new '$OUTPUT_SCRIPT'..."
cat << 'EOF' > "$OUTPUT_SCRIPT"
#!/bin/bash

# ==============================================================================
# This is a self-contained script that recreates a complete project structure
# including all files and their contents.
#
# This script was automatically generated by 'setup_project_script_maker.sh'.
#
# Usage:
#   1. Make this script executable: chmod +x setup_project.sh
#   2. Run it: ./setup_project.sh
# ==============================================================================

set -e

PROJECT_NAME="my_project"

echo "Creating the project structure for '$PROJECT_NAME'..."
mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

echo "Creating directories..."
EOF

# --- Add directories first ---
find "$PROJECT_ROOT_DIR" -type d | while read -r dir; do
    relative_path="${dir#$PROJECT_ROOT_DIR/}"
    [[ -z "$relative_path" ]] && continue
    if ! should_ignore "$relative_path"; then
        echo "mkdir -p \"$relative_path\"" >> "$OUTPUT_SCRIPT"
    fi
done

# --- Add files after directories ---
find "$PROJECT_ROOT_DIR" -type f | while read -r file; do
    relative_path="${file#$PROJECT_ROOT_DIR/}"
    if ! should_ignore "$relative_path"; then
        echo "" >> "$OUTPUT_SCRIPT"
        echo "echo \"Creating file: $relative_path\"" >> "$OUTPUT_SCRIPT"
        echo "cat << 'EOF' > \"$relative_path\"" >> "$OUTPUT_SCRIPT"
        cat "$file" >> "$OUTPUT_SCRIPT"
        echo "EOF" >> "$OUTPUT_SCRIPT"
    fi
done

# Footer
cat << 'EOF' >> "$OUTPUT_SCRIPT"

echo "----------------------------------------------------"
echo "Project '$PROJECT_NAME' has been successfully created."
echo "You can now navigate into the new directory: cd '$PROJECT_NAME'"
echo "----------------------------------------------------"

EOF

chmod +x "$OUTPUT_SCRIPT"
echo "The script '$OUTPUT_SCRIPT' has been created and is ready to use."
