#!/bin/bash

# ==============================================================================
# This is a self-contained script that recreates a complete project structure
# including all files and their contents.
#
# This script was automatically generated by 'setup_project_script_maker.sh'.
#
# Usage:
#   1. Make this script executable: chmod +x setup_project.sh
#   2. Run it: ./setup_project.sh
# ==============================================================================

# Exit immediately if a command exits with a non-zero status.
set -e

PROJECT_NAME="my_project"

echo "Creating the project structure for '$PROJECT_NAME'..."
mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

echo "Creating directories..."

mkdir -p "/mnt/data/build/ebooks-manager"

echo "Creating file: .env.example"
cat << 'EOF' > ".env.example"
# User and Group IDs
PUID=1000
PGID=1000

# Timezone
TZ=Asia/Kolkata

# Logging
LOG_LEVEL=DEBUG

# FlareSolverr
FLARESOLVERR_URL=http://flaresolverr:8191/v1

# Flask
FLASK_HOST=0.0.0.0
FLASK_PORT=5002

# Application
DRY_RUN=yes
PYTHONUNBUFFERED=1
WEBPAGE_CACHE_DAYS=30
EOF
mkdir -p "data"
mkdir -p "data/cache"
mkdir -p "data/cache/search_results"
mkdir -p "data/cache/search_results/cwa_book_downloader"
mkdir -p "data/cache/logins"
mkdir -p "data/cache/logins/cwa_book_downloader"
mkdir -p "data/cache/logins/cwa"
mkdir -p "data/cache/logins/goodreads"
mkdir -p "data/cache/webpages"
mkdir -p "data/cache/webpages/storybook"
mkdir -p "data/cache/webpages/storybook/others"
mkdir -p "data/cache/webpages/storybook/ebooks"
mkdir -p "data/cache/webpages/hardcover"
mkdir -p "data/cache/webpages/hardcover/others"
mkdir -p "data/cache/webpages/hardcover/ebooks"
mkdir -p "data/cache/webpages/goodreads"
mkdir -p "data/cache/webpages/goodreads/others"
mkdir -p "data/cache/webpages/goodreads/ebooks"
mkdir -p "data/databases"
mkdir -p "scripts"

echo "Creating file: scripts/entrypoint.sh"
cat << 'EOF' > "scripts/entrypoint.sh"
#!/bin/bash
set -e

# Run bootstrap with error logging
echo "Running bootstrap..."
if ! python /app/src/bootstrap.py; then
    echo "Bootstrap failed, exiting."
    exit 1
fi

# Ensure config file exists
if [ ! -f /app/config/config.json ]; then
    cp /app/config/config.json.template /app/config/config.json
    echo "Created config.json from template. Please update it with your credentials or use environment variables."
    exit 1
fi

# Run Gunicorn in the background with logging
echo "Starting Gunicorn..."
gunicorn --bind 0.0.0.0:5002 --workers 1 --threads 2 --timeout 120 --log-file /app/logs/gunicorn.log src.webui.app:app &

# Run the scheduler in the foreground
echo "Starting scheduler..."
exec python3 /app/src/job_runner.py
EOF

echo "Creating file: scripts/script.sh"
cat << 'EOF' > "scripts/script.sh"
#!/bin/bash
set -e

# Example script for running the project or performing maintenance tasks
exec python3 /app/src/main.py
EOF
mkdir -p "config"

echo "Creating file: config/config.json.template"
cat << 'EOF' > "config/config.json.template"
{
  "goodreads_username": "your_goodreads_email",
  "goodreads_password": "your_goodreads_password",
  "goodreads_user_id": "your_goodreads_user_id",
  "cwa_api_url": "http://calibre-web:8084/request/api",
  "cwa_username": "your_cwa_username",
  "cwa_password": "your_cwa_password",
  "database_path": "/app/data/databases/goodreads.db",
  "log_file": "/app/logs/sync_log.txt",
  "history_file": "/app/logs/history.json",
  "cache_dir": "/app/data/cache"
}
EOF
mkdir -p "logs"

echo "Creating file: logs/sync_log.txt"
cat << 'EOF' > "logs/sync_log.txt"
EOF

echo "Creating file: logs/history.json"
cat << 'EOF' > "logs/history.json"
EOF
mkdir -p "logs/screenshots"

echo "Creating file: requirements.txt"
cat << 'EOF' > "requirements.txt"
requests==2.31.0
beautifulsoup4==4.12.2
flask==3.0.3
selenium==4.23.1
gunicorn==20.1.0
apscheduler==3.10.4
Pillow==10.1.0EOF

echo "Creating file: Dockerfile"
cat << 'EOF' > "Dockerfile"
FROM python:3.9-slim

WORKDIR /app

# Set up non-root user
RUN useradd -m -r -u 1000 appuser && \
    mkdir -p /home/appuser/.cache && \
    chown -R appuser:appuser /app /home/appuser

# Install essential tools and ARM64-compatible Chromium
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    gnupg \
    unzip \
    ca-certificates \
    jq \
    chromium \
    chromium-driver \
    libglib2.0-0 \
    libnss3 \
    libdbus-1-3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libpango-1.0-0 \
    libcairo2 \
    libasound2 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Verify ChromeDriver exists and set permissions
RUN if [ ! -f /usr/bin/chromedriver ]; then echo "ChromeDriver not found"; exit 1; fi && \
    chmod 755 /usr/bin/chromedriver && \
    chown appuser:appuser /usr/bin/chromedriver

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip cache purge

# Copy application code
COPY . .
# Ensure ownership of all app files and logs
RUN chown -R appuser:appuser /app /home/appuser && \
    mkdir -p /app/logs && \
    chown appuser:appuser /app/logs

# Set environment variables
ENV PYTHONPATH=/app \
    CHROMEDRIVER_PATH=/usr/bin/chromedriver \
    PATH="/home/appuser/.local/bin:$PATH"

# Switch to non-root user
USER appuser

# Entry point
CMD ["/app/scripts/entrypoint.sh"]EOF
mkdir -p "src"

echo "Creating file: src/bootstrap.py"
cat << 'EOF' > "src/bootstrap.py"
import os
from pathlib import Path
import json
import sys

REQUIRED_CONFIG_KEYS = ['goodreads_username', 'goodreads_password', 'goodreads_user_id', 'cwa_api_url', 'cwa_username', 'cwa_password', 'database_path', 'log_file', 'history_file', 'cache_dir']

def check_and_create_app_files():
    """
    Ensures that all necessary config, log, and data directories and files exist before the main application starts.
    Handles errors gracefully and validates configurations.
    """
    print("Running bootstrap checks...")

    try:
        # --- Define Core Paths (with env overrides) ---
        app_dir = Path(os.getenv('APP_DIR', '/app'))
        config_dir = app_dir / 'config'
        log_dir = app_dir / 'logs'
        data_dir = app_dir / 'data'

        # --- All Directories ---
        dirs_to_create = [
            config_dir,
            log_dir,
            log_dir / 'screenshots',
            data_dir,
            data_dir / 'databases',
            data_dir / 'cache' / 'logins' / 'goodreads',
            data_dir / 'cache' / 'logins' / 'cwa',
            data_dir / 'cache' / 'logins' / 'cwa_book_downloader',
            data_dir / 'cache' / 'search_results' / 'cwa_book_downloader',
            data_dir / 'cache' / 'webpages' / 'goodreads' / 'ebooks',
            data_dir / 'cache' / 'webpages' / 'goodreads' / 'others',
            data_dir / 'cache' / 'webpages' / 'storybook' / 'ebooks',
            data_dir / 'cache' / 'webpages' / 'storybook' / 'others',
            data_dir / 'cache' / 'webpages' / 'hardcover' / 'ebooks',
            data_dir / 'cache' / 'webpages' / 'hardcover' / 'others',
            data_dir / 'cache' / 'webpages' / 'goodreads' / 'shelves',
        ]

        for dir_path in dirs_to_create:
            dir_path.mkdir(parents=True, exist_ok=True)
            print(f"Ensured directory exists: {dir_path}")

        # --- Config File ---
        config_file = config_dir / 'config.json'
        config_template = config_dir / 'config.json.template'

        if not config_file.exists():
            if config_template.exists():
                print(f"'{config_file}' not found. Creating from template.")
                config_file.write_text(config_template.read_text())
            else:
                print(f"'{config_template}' not found. Creating with default values.")
                default_config = {
                    "goodreads_username": "your_goodreads_email",
                    "goodreads_password": "your_goodreads_password",
                    "goodreads_user_id": "your_goodreads_user_id",
                    "cwa_api_url": "http://calibre-web:8084/request/api",
                    "cwa_username": "your_cwa_username",
                    "cwa_password": "your_cwa_password",
                    "database_path": "/app/data/databases/goodreads.db",
                    "log_file": "/app/logs/sync_log.txt",
                    "history_file": "/app/logs/history.json",
                    "cache_dir": "/app/data/cache"
                }
                config_file.write_text(json.dumps(default_config, indent=2))

        # Validate config
        try:
            with open(config_file, 'r') as f:
                config = json.load(f)
            missing_keys = [key for key in REQUIRED_CONFIG_KEYS if key not in config]
            if missing_keys:
                raise ValueError(f"Config missing required keys: {missing_keys}")
            print("Config validated successfully.")
        except (json.JSONDecodeError, ValueError) as e:
            print(f"Invalid config: {e}. Please fix '{config_file}'.")
            sys.exit(1)

        # --- Log and History Files ---
        log_file = log_dir / 'sync_log.txt'
        history_file = log_dir / 'history.json'
        db_file = data_dir / 'databases' / 'goodreads.db'

        files_to_touch = [log_file, history_file, db_file]
        for file_path in files_to_touch:
            if not file_path.exists():
                print(f"Creating empty '{file_path.name}'.")
                file_path.touch()

        print("Bootstrap checks complete. All necessary files and directories are present.")
    except Exception as e:
        print(f"Bootstrap failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    check_and_create_app_files()
EOF
mkdir -p "src/api"

echo "Creating file: src/api/cwa_client.py"
cat << 'EOF' > "src/api/cwa_client.py"
import requests
import json
from pathlib import Path
import time
import logging

class CWAClient:
    def __init__(self, api_url, username, password, cache_dir):
        self.api_url = api_url
        self.auth = (username, password)
        self.cache_dir = Path(cache_dir) / 'cwa_book_downloader' / 'search_results'
        self.cache_dir.mkdir(parents=True, exist_ok=True)

    def search_book(self, query, language='en'):
        try:
            search_url = f"{self.api_url}/search"
            search_data = {'query': query, 'language': language}
            response = requests.post(search_url, json=search_data, auth=self.auth)
            response.raise_for_status()
            results = response.json()
            
            # Cache results
            cache_file = self.cache_dir / f"{query.replace(' ', '_')}.json"
            with open(cache_file, 'w') as f:
                json.dump(results, f)
                
            return results
        except requests.RequestException as e:
            logging.error(f"Search request failed: {e}", exc_info=True)
            return None

    def request_download(self, result_id, book_format='epub'):
        try:
            download_url = f"{self.api_url}/download"
            download_data = {'result_id': result_id, 'format': book_format}
            response = requests.post(download_url, json=download_data, auth=self.auth)
            response.raise_for_status()
            return response.json().get('download_id')
        except requests.RequestException as e:
            logging.error(f"Download request failed: {e}", exc_info=True)
            return None

    def check_download_status(self, download_id, max_attempts=10, wait_seconds=10):
        status_url = f"{self.api_url}/status/{download_id}"
        for _ in range(max_attempts):
            try:
                response = requests.get(status_url, auth=self.auth)
                response.raise_for_status()
                status = response.json().get('status')
                if status == 'success':
                    return True
                elif status == 'failure':
                    return False
                time.sleep(wait_seconds)
            except requests.RequestException as e:
                logging.error(f"Status check failed: {e}", exc_info=True)
                time.sleep(wait_seconds)
        return False
EOF

echo "Creating file: src/api/__init__.py"
cat << 'EOF' > "src/api/__init__.py"
EOF

echo "Creating file: src/sync_logic.py"
cat << 'EOF' > "src/sync_logic.py"
import logging
from src.scrapers.goodreads import GoodreadsScraper
from src.scrapers.hardcover import HardcoverScraper
from src.scrapers.storygraph import StorygraphScraper
from src.utils.config_loader import load_config

def orchestrate_sync():
    config = load_config()
    logger = logging.getLogger()

    # Initialize scrapers
    goodreads_scraper = GoodreadsScraper(config)
    hardcover_scraper = HardcoverScraper(config)
    storygraph_scraper = StorygraphScraper(config)

    # Run Goodreads sync
    logger.info("Starting Goodreads sync")
    try:
        goodreads_scraper.sync()
        logger.info("Goodreads sync completed")
    except Exception as e:
        logger.error(f"Goodreads sync failed: {e}", exc_info=True)

    # Placeholder for other scrapers
    logger.info("Hardcover and Storygraph sync not implemented yet")
    # hardcover_scraper.sync()
    # storygraph_scraper.sync()
EOF

echo "Creating file: src/main.py"
cat << 'EOF' > "src/main.py"
from src.utils.config_loader import load_config
from src.utils.logger import setup_logger
from src.sync_logic import orchestrate_sync
import os

def main():
    config = load_config()
    log_level = os.getenv('LOG_LEVEL', 'INFO').upper()
    logger = setup_logger(config['log_file'], log_level)
    orchestrate_sync()

if __name__ == "__main__":
    main()
EOF
mkdir -p "src/scrapers"

echo "Creating file: src/scrapers/hardcover.py"
cat << 'EOF' > "src/scrapers/hardcover.py"
# Placeholder for Hardcover scraper
class HardcoverScraper:
    def __init__(self, config):
        pass

    def sync(self):
        pass
EOF

echo "Creating file: src/scrapers/storygraph.py"
cat << 'EOF' > "src/scrapers/storygraph.py"
# Placeholder for Storygraph scraper
class StorygraphScraper:
    def __init__(self, config):
        pass

    def sync(self):
        pass
EOF

echo "Creating file: src/scrapers/goodreads.py"
cat << 'EOF' > "src/scrapers/goodreads.py"
# src/scrapers/goodreads.py
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, WebDriverException
from bs4 import BeautifulSoup
from pathlib import Path
import json
import logging
import time
import os
import requests
import pickle
from datetime import datetime
from urllib.parse import urljoin

from src.utils.database import Database
from src.api.cwa_client import CWAClient

LOG = logging.getLogger(__name__)

# Common cookie names that often indicate an authenticated session
LIKELY_SESSION_COOKIE_NAMES = [
    'session-id', 'sess', 's', 'auth_token', 'gr_user', 'cgcsess', 'session', 'csm-hit'
]

class GoodreadsScraper:
    def __init__(self, config):
        self.config = config
        self.user_id = config.get('goodreads_user_id')
        self.goodreads_email = config.get('goodreads_username')
        self.goodreads_password = config.get('goodreads_password')
        self.shelf_name = 'to-download'
        self.base_url = 'https://www.goodreads.com'
        self.cache_dir = Path(config.get('cache_dir', '/app/data/cache')) / 'webpages' / 'goodreads' / 'ebooks'
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.screenshot_dir = Path(config.get('log_file', '/app/logs/sync_log.txt')).parent / 'screenshots'
        self.screenshot_dir.mkdir(parents=True, exist_ok=True)
        self.cookie_file = Path(config.get('cache_dir', '/app/data/cache')) / 'logins' / 'goodreads' / 'cookies.pkl'
        self.cookie_file.parent.mkdir(parents=True, exist_ok=True)
        self.db = Database(config.get('database_path'))
        self.cwa_client = CWAClient(
            config.get('cwa_api_url'),
            config.get('cwa_username'),
            config.get('cwa_password'),
            config.get('cache_dir')
        )
        self.is_debug = os.getenv('LOG_LEVEL', 'INFO').upper() == 'DEBUG'
        self.dry_run = os.getenv('DRY_RUN', 'no').lower() == 'yes'
        self.driver = None
        self.logged_in = False
        self._selenium_available = True

    def _init_driver(self):
        if self.driver:
            return self.driver
        try:
            options = Options()
            headless = os.getenv('HEADLESS', '1') == '1'
            if headless:
                options.add_argument('--headless=new')
            options.add_argument('--no-sandbox')
            options.add_argument('--disable-dev-shm-usage')
            options.add_argument('--disable-gpu')
            options.add_argument('--disable-extensions')
            options.add_argument('--window-size=1920,1080')
            ua = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
            options.add_argument(f'user-agent={ua}')
            chromium_bin = os.getenv('CHROMIUM_BIN', '/usr/bin/chromium')
            if Path(chromium_bin).exists():
                options.binary_location = chromium_bin

            chromedriver_path = os.getenv('CHROMEDRIVER_PATH', '/usr/bin/chromedriver')
            if not Path(chromedriver_path).exists():
                LOG.error("ChromeDriver not found at %s", chromedriver_path)
                self._selenium_available = False
                return None

            service = Service(executable_path=chromedriver_path)
            self.driver = webdriver.Chrome(service=service, options=options)
            LOG.info("Driver initialized successfully")
            return self.driver
        except WebDriverException as e:
            LOG.error("Failed to initialize driver: %s", e, exc_info=True)
            self._selenium_available = False
            return None

    def _close_driver(self):
        if self.driver:
            try:
                self.driver.quit()
            except Exception:
                pass
        self.driver = None
        self.logged_in = False

    def _take_screenshot(self, name, force=False):
        """
        Save a screenshot and overlay the current URL at the top.
        If Pillow is unavailable or overlay fails, still save the raw screenshot.
        """
        if not self.driver or not (self.is_debug or force):
            return
        try:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            path = self.screenshot_dir / f"{name}_{ts}.png"
            # try to set window size to full page height (best effort)
            try:
                height = self.driver.execute_script(
                    "return Math.max(document.body.scrollHeight, document.documentElement.scrollHeight);"
                )
                width = self.driver.execute_script(
                    "return Math.max(document.body.scrollWidth, document.documentElement.scrollWidth);"
                )
                w = min(2400, int(width) if width else 1920)
                h = min(6000, int(height) if height else 1080)
                self.driver.set_window_size(w, h)
                time.sleep(0.2)
            except Exception:
                pass

            # save raw screenshot
            self.driver.save_screenshot(str(path))
            LOG.info("Saved screenshot: %s", path)

            # try overlaying URL using Pillow
            try:
                from PIL import Image, ImageDraw, ImageFont
                img = Image.open(path)
                draw = ImageDraw.Draw(img)
                try:
                    url_text = self.driver.current_url or ""
                except Exception:
                    url_text = ""
                bar_height = max(28, int(img.height * 0.04))
                # draw top bar
                draw.rectangle([(0, 0), (img.width, bar_height)], fill=(30, 30, 30))
                # font (defensive)
                try:
                    font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", size=max(12, bar_height - 10))
                except Exception:
                    font = ImageFont.load_default()
                # compute text height/width robustly
                display_text = url_text if len(url_text) <= 140 else ("..." + url_text[-137:])
                try:
                    # Pillow >= 8: textbbox available
                    bbox = draw.textbbox((0, 0), display_text, font=font)
                    text_w = bbox[2] - bbox[0]
                    text_h = bbox[3] - bbox[1]
                except Exception:
                    # fallback older method
                    try:
                        text_w, text_h = draw.textsize(display_text, font=font)
                    except Exception:
                        text_w, text_h = (0, bar_height - 6)
                padding = 8
                y = int((bar_height - text_h) / 2)
                draw.text((padding, y), display_text, fill=(255, 255, 255), font=font)
                # save overlay (overwrite)
                img.save(path)
                LOG.info("Saved screenshot with URL overlay: %s (url=%s)", path, url_text)
            except Exception as e:
                LOG.warning("URL overlay failed (Pillow missing or error): %s", e)
        except Exception as e:
            LOG.warning("Screenshot failed: %s", e)

    def _save_cookies(self):
        if not self.driver:
            return
        try:
            with open(self.cookie_file, 'wb') as f:
                pickle.dump(self.driver.get_cookies(), f)
            LOG.info("Saved selenium cookies to %s", self.cookie_file)
        except Exception as e:
            LOG.error("Failed to save cookies: %s", e, exc_info=True)

    def _load_cookies_to_selenium(self):
        if not self.driver or not self.cookie_file.exists():
            LOG.debug("No cookies available for selenium load")
            return False
        try:
            with open(self.cookie_file, 'rb') as f:
                cookies = pickle.load(f)
            # Navigate to base domain before adding cookies
            self.driver.get(self.base_url)
            for c in cookies:
                try:
                    c.pop('sameSite', None)
                    if 'expiry' in c and isinstance(c['expiry'], float):
                        c['expiry'] = int(c['expiry'])
                    if 'domain' in c and c['domain'].startswith('.'):
                        c['domain'] = c['domain'].lstrip('.')
                    self.driver.add_cookie(c)
                except Exception:
                    LOG.debug("Skipping invalid cookie: %s", c)
            LOG.info("Loaded cookies into selenium")
            return True
        except Exception as e:
            LOG.error("Failed to load cookies for selenium: %s", e, exc_info=True)
            return False

    def _load_cookies_into_requests(self):
        s = requests.Session()
        if not self.cookie_file.exists():
            return s
        try:
            with open(self.cookie_file, 'rb') as f:
                cookies = pickle.load(f)
            for c in cookies:
                domain = c.get('domain', '.goodreads.com')
                name = c.get('name')
                value = c.get('value')
                path = c.get('path', '/')
                if name and value:
                    s.cookies.set(name, value, domain=domain, path=path)
            LOG.info("Loaded cookies into requests session")
        except Exception as e:
            LOG.warning("Failed to load cookies into requests: %s", e)
        return s

    def _cookies_indicate_logged_in(self, cookies):
        for c in cookies:
            name = c.get('name') if isinstance(c, dict) else None
            if not name:
                continue
            if any(sn in name.lower() for sn in LIKELY_SESSION_COOKIE_NAMES):
                return True
        return False

    def _verify_logged_in_selenium(self):
        """
        Return True if any positive login indicator is present:
         - session cookie names
         - profile / signout selectors
         - 'My Books' link
         - absence of sign-in inputs/buttons
        """
        driver = self.driver
        try:
            # cookie check
            try:
                cookies = driver.get_cookies()
                if cookies and self._cookies_indicate_logged_in(cookies):
                    LOG.debug("Detected session cookie(s) after login flow")
                    return True
            except Exception:
                LOG.debug("Couldn't read cookies in verify step")

            selectors = [
                "a[href*='/user/sign_out']",
                "a[href*='/logout']",
                "a[href*='/user/show/']",
                "img.gravatar",
                "button[aria-label='Account menu']"
            ]
            for s in selectors:
                try:
                    el = driver.find_elements(By.CSS_SELECTOR, s)
                    if el and len(el) > 0:
                        LOG.debug("Found logged-in indicator element selector: %s", s)
                        return True
                except Exception:
                    continue

            # 'My Books' check
            try:
                if driver.find_elements(By.XPATH, "//a[contains(., 'My Books') or contains(., 'My books')]"):
                    LOG.debug("Found 'My Books' link (likely logged-in)")
                    return True
            except Exception:
                pass

            # absence of sign-in inputs/buttons
            signin_inputs = []
            try:
                signin_inputs = (
                    driver.find_elements(By.ID, "ap_email")
                    + driver.find_elements(By.NAME, "user[email]")
                    + driver.find_elements(By.XPATH, "//button[contains(., 'Sign in') or contains(., 'Sign-In')]")
                )
            except Exception:
                signin_inputs = []
            if not signin_inputs:
                LOG.debug("No sign-in inputs/buttons found on page; assume logged in")
                return True

        except Exception as e:
            LOG.debug("verify_logged_in_selenium encountered an error: %s", e, exc_info=True)
        return False

    def _wait_for_login_success(self, timeout=30, poll=0.5):
        start = time.time()
        while time.time() - start < timeout:
            try:
                if self._verify_logged_in_selenium():
                    LOG.info("Login verified by _wait_for_login_success")
                    return True
            except Exception:
                LOG.debug("Exception while checking login status", exc_info=True)
            time.sleep(poll)
        LOG.debug("Timed out waiting for login success")
        return False

    def login(self):
        if self.logged_in:
            LOG.info("Already logged in")
            return True

        driver = self._init_driver()
        if not driver:
            LOG.warning("Selenium not available; will attempt requests fallback using cookies.")
            return False

        # Try cookie restore
        try:
            driver.get(self.base_url)
            if self.cookie_file.exists():
                LOG.info("Attempting cookie-based login for selenium")
                self._load_cookies_to_selenium()
                driver.refresh()
                time.sleep(1)
                if self._verify_logged_in_selenium():
                    LOG.info("Logged in using saved cookies (selenium)")
                    self.logged_in = True
                    return True
                else:
                    LOG.info("Saved cookies are invalid. Proceeding with full login.")
        except Exception as e:
            LOG.warning("Cookie-based login attempt failed: %s", e, exc_info=True)

        # Full login flow
        tries = 3
        for attempt in range(1, tries + 1):
            try:
                LOG.info("Navigating to Goodreads sign-in page.")
                driver.get(f"{self.base_url}/user/sign_in")
                self._take_screenshot("signin_portal_page")

                # Click sign-in button if present (Best-effort)
                try:
                    btn = WebDriverWait(driver, 6).until(
                        EC.element_to_be_clickable((By.XPATH, "//button[contains(normalize-space(.),'Sign in with email') or contains(normalize-space(.),'Sign in with Amazon') or contains(normalize-space(.),'Sign in')]"))
                    )
                    try:
                        btn.click()
                        LOG.info("Clicked 'Sign in with email' button.")
                        time.sleep(0.8)
                    except Exception:
                        LOG.debug("Couldn't click sign-in button (will continue).")
                except TimeoutException:
                    LOG.debug("'Sign in with email' button not found, continue to locate inputs")

                # find credentials fields
                email_el = None
                password_el = None
                try:
                    email_el = WebDriverWait(driver, 8).until(
                        EC.presence_of_element_located((By.ID, "ap_email"))
                    )
                    password_el = driver.find_element(By.ID, "ap_password")
                    LOG.debug("Found Amazon ap_email/ap_password fields")
                except TimeoutException:
                    try:
                        email_el = WebDriverWait(driver, 6).until(
                            EC.presence_of_element_located((By.NAME, "user[email]"))
                        )
                        password_el = driver.find_element(By.NAME, "user[password]")
                        LOG.debug("Found Goodreads native fields")
                    except TimeoutException:
                        email_el = None
                        password_el = None

                if not email_el or not password_el:
                    self._take_screenshot(f"error_login_attempt_{attempt}", force=True)
                    raise Exception("Login form fields could not be located")

                # try "Keep me signed in"
                try:
                    for sel in [
                        (By.ID, "rememberMe"),
                        (By.NAME, "rememberMe"),
                        (By.XPATH, "//input[@type='checkbox' and (contains(@id,'remember') or contains(@name,'remember'))]"),
                        (By.XPATH, "//label[contains(., 'Keep me signed in')]/preceding-sibling::input[@type='checkbox']"),
                        (By.XPATH, "//span[contains(., 'Keep me signed in')]/preceding::input[1][@type='checkbox']")
                    ]:
                        try:
                            cb = driver.find_element(*sel)
                            if cb and not cb.is_selected():
                                cb.click()
                                LOG.info("Checked 'Keep me signed in' checkbox using selector %s", sel)
                                break
                        except Exception:
                            continue
                except Exception:
                    LOG.debug("Could not check 'Keep me signed in'")

                # enter credentials and submit
                LOG.info("Entering credentials (masked).")
                email_el.clear()
                email_el.send_keys(self.goodreads_email)
                password_el.clear()
                password_el.send_keys(self.goodreads_password)

                submitted = False
                for submit_selector in [
                    (By.ID, "signInSubmit"),
                    (By.XPATH, "//input[@type='submit' and (contains(@value,'Sign') or contains(@value,'sign'))]"),
                    (By.XPATH, "//button[contains(., 'Sign in') or contains(., 'Sign-In')]")
                ]:
                    try:
                        btn = driver.find_element(*submit_selector)
                        btn.click()
                        submitted = True
                        LOG.debug("Clicked submit: %s", submit_selector)
                        break
                    except Exception:
                        continue

                if not submitted:
                    from selenium.webdriver.common.keys import Keys
                    try:
                        password_el.send_keys(Keys.RETURN)
                        LOG.debug("Submitted via Enter key")
                    except Exception:
                        pass

                success = self._wait_for_login_success(timeout=30)
                if success:
                    self._take_screenshot("login_success")
                    self._save_cookies()
                    self.logged_in = True
                    LOG.info("Successfully logged in (selenium)")
                    return True
                else:
                    self._take_screenshot(f"error_login_attempt_{attempt}", force=True)
                    raise Exception("Timed out waiting for login success indicators")

            except Exception as exc:
                LOG.warning("Login attempt %d failed: %s", attempt, exc, exc_info=True)
                time.sleep(2 + attempt * 2)
                if attempt == tries:
                    LOG.error("Exhausted login attempts")
                    break
                continue

        self._close_driver()
        return False

    def _fetch_shelf_with_requests(self, shelf_name):
        session = self._load_cookies_into_requests()
        shelf_url = f"{self.base_url}/review/list/{self.user_id}?shelf={shelf_name}"
        try:
            r = session.get(shelf_url, timeout=20)
            if r.status_code == 200 and "Sign in" not in r.text:
                LOG.info("Fetched shelf via requests fallback")
                return r.text
            LOG.warning("Requests fallback couldn't fetch shelf (status=%s)", r.status_code)
            return None
        except Exception as e:
            LOG.error("Requests fetch failed: %s", e, exc_info=True)
            return None

    def get_goodreads_books_from_shelf(self, shelf_name):
        LOG.info("Fetching books from Goodreads '%s' shelf for user_id=%s...", shelf_name, self.user_id)
        page_source = None

        # Selenium path
        if self._selenium_available:
            try:
                ok = self.login()
            except Exception as e:
                LOG.warning("Selenium login error: %s", e, exc_info=True)
                ok = False

            if ok and self.driver:
                try:
                    shelf_url = f"{self.base_url}/review/list/{self.user_id}?shelf={shelf_name}"
                    LOG.debug("Navigating selenium to: %s", shelf_url)
                    self.driver.get(shelf_url)

                    # Wait for the shelf table rows to appear (robust)
                    try:
                        WebDriverWait(self.driver, 20).until(
                            lambda d: d.find_elements(By.CSS_SELECTOR, "tbody#booksBody tr, tr.bookalike, table#books tr, td.field.title a")
                        )
                    except TimeoutException:
                        LOG.debug("Timeout while waiting for shelf table - will continue to parse whatever is available")

                    self._take_screenshot(f"fetch_shelf_{shelf_name}")
                    page_source = self.driver.page_source
                except Exception as e:
                    LOG.error("Selenium fetch of shelf failed: %s", e, exc_info=True)
                    self._take_screenshot("fetch_shelf_error", force=True)
                    page_source = None
            else:
                page_source = None

        # Requests fallback
        if not page_source:
            LOG.info("Attempting requests fallback to fetch shelf")
            page_source = self._fetch_shelf_with_requests(shelf_name)

        if not page_source:
            LOG.error("Unable to fetch shelf page via selenium or requests fallback")
            return []

        # Save raw HTML for debugging
        try:
            fname = self.cache_dir / f"shelf_{shelf_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
            fname.write_text(page_source, encoding='utf-8')
            LOG.debug("Saved shelf HTML to %s", fname)
        except Exception:
            pass

        soup = BeautifulSoup(page_source, 'html.parser')
        books = []

        # Robust row selection - try several strongly-typed selectors in order
        candidate_rows = []
        selectors_tried = []
        try:
            # prefer explicit tbody id
            selectors_tried.append("tbody#booksBody tr")
            candidate_rows = soup.select("tbody#booksBody tr")
            if not candidate_rows:
                selectors_tried.append("tr.bookalike")
                candidate_rows = soup.select("tr.bookalike")
            if not candidate_rows:
                selectors_tried.append("table#books tr")
                candidate_rows = soup.select("table#books tr")
            if not candidate_rows:
                selectors_tried.append("table.table tr")
                candidate_rows = soup.select("table.table tr")
            if not candidate_rows:
                selectors_tried.append("td.field.title a")
                # fallback: find title anchors directly
                title_anchors = soup.select("td.field.title a, a.bookTitle, a.title")
                # map anchors back to rows
                for a in title_anchors:
                    tr = a.find_parent("tr")
                    if tr is not None:
                        candidate_rows.append(tr)
            LOG.debug("Selectors tried: %s ; candidate rows found: %d", selectors_tried, len(candidate_rows))
        except Exception:
            LOG.debug("Error when selecting candidate rows", exc_info=True)

        for row in candidate_rows:
            try:
                # Title and author live in td.field.title and td.field.author (per your HTML)
                title_elem = row.select_one('td.field.title a') or row.select_one('a.bookTitle') or row.select_one('a.title')
                author_elem = row.select_one('td.field.author a') or row.select_one('a.authorName') or row.select_one('.authorName')
                if not (title_elem and author_elem):
                    # some row formats may wrap differently; try finding anchors anywhere in row
                    title_elem = row.find('a', href=True, title=True) or title_elem
                    author_elem = row.find('a', href=True, text=True) or author_elem
                if not (title_elem and author_elem):
                    LOG.debug("Skipping row because title or author missing")
                    continue

                title = title_elem.get_text(strip=True)
                author = author_elem.get_text(strip=True)
                book_url = title_elem.get('href')
                goodreads_id = None
                if book_url:
                    parts = [p for p in book_url.split('/') if p]
                    for p in reversed(parts):
                        if p.isdigit():
                            goodreads_id = p
                            break
                # if still no numeric id, try data attributes or review id in tr id: e.g. id="review_7903565710"
                if not goodreads_id:
                    # check for data-resource-id or similar attributes on row or cover anchor
                    for attr in ('data-resource-id', 'data-book-id'):
                        if row.has_attr(attr):
                            goodreads_id = row[attr]
                            break
                    if not goodreads_id and row.has_attr('id'):
                        # extract digits
                        import re
                        m = re.search(r'(\d{6,})', row['id'])
                        if m:
                            goodreads_id = m.group(1)

                if not goodreads_id:
                    LOG.debug("Skipping book with no ID: %s", title)
                    continue

                books.append({
                    'goodreads_id': goodreads_id,
                    'title': title,
                    'author': author,
                    'book_url': urljoin(self.base_url, book_url) if book_url else None
                })
            except Exception:
                LOG.debug("Skipping malformed row", exc_info=True)
                continue

        LOG.info("Found %d books on shelf %s", len(books), shelf_name)
        try:
            self._close_driver()
        except Exception:
            pass
        return books

    def update_history(self, entry):
        history_path = Path(self.config.get('history_file', '/app/logs/history.json'))
        entry['timestamp'] = datetime.now().isoformat()
        try:
            history = []
            if history_path.exists() and history_path.stat().st_size > 0:
                history = json.loads(history_path.read_text())
            history.append(entry)
            history_path.write_text(json.dumps(history, indent=2))
        except Exception:
            LOG.warning("Failed to update history file", exc_info=True)

    def sync(self):
        books = self.get_goodreads_books_from_shelf(self.shelf_name)
        if not books:
            LOG.warning("No books found, skipping sync")
            return
        for b in books:
            d = {'goodreads_id': b['goodreads_id'], 'title': b['title'], 'author': b['author']}
            self.db.save_book(d)
            self.update_history({'action': 'fetch_shelf', 'book_id': d['goodreads_id'], 'title': d['title'], 'status': 'success'})
            query = f"{d['title']} {d['author']}"
            results = self.cwa_client.search_book(query)
            if not results or not results.get('results'):
                self.update_history({'action':'search','book_id':d['goodreads_id'],'title':d['title'],'status':'no_results'})
                continue
            if self.dry_run:
                self.update_history({'action':'download','book_id':d['goodreads_id'],'title':d['title'],'status':'skipped_dry_run'})
                continue
            best = results['results'][0]
            download_id = self.cwa_client.request_download(best['id'])
            if not download_id:
                continue
            success = self.cwa_client.check_download_status(download_id)
            self.update_history({'action':'download','book_id':d['goodreads_id'],'title':d['title'],'result_id':best['id'],'status':'success' if success else 'failure'})
EOF

echo "Creating file: src/scrapers/__init__.py"
cat << 'EOF' > "src/scrapers/__init__.py"
EOF
mkdir -p "src/webui"

echo "Creating file: src/webui/app.py"
cat << 'EOF' > "src/webui/app.py"
from flask import Flask, render_template, jsonify, request
from pathlib import Path
import logging
from datetime import datetime
import json
from src.utils.config_loader import load_config
from src.sync_logic import orchestrate_sync
from src.scrapers.goodreads import GoodreadsScraper

app = Flask(__name__)

logging.basicConfig(level=logging.INFO)

@app.template_filter('strftime')
def _jinja2_filter_datetime(date_str, fmt='%Y-%m-%d %H:%M:%S'):
    if not date_str:
        return "N/A"
    try:
        if isinstance(date_str, str):
            dt = datetime.fromisoformat(date_str)
        elif isinstance(date_str, datetime):
            dt = date_str
        else:
            return date_str
        return dt.strftime(fmt)
    except (ValueError, TypeError):
        return date_str

@app.route('/')
@app.route('/status')
def status():
    history_path = Path('/app/logs/history.json')
    history = []
    log_path = Path('/app/logs/sync_log.txt')
    log_content = ""
    if history_path.exists():
        try:
            with open(history_path, 'r') as f:
                content = f.read()
                if content:
                    history = json.loads(content)
                    history.reverse()
        except json.JSONDecodeError:
            logging.warning("History file is malformed or empty.")
        except Exception as e:
            logging.error(f"Error reading history file: {e}", exc_info=True)
    try:
        if log_path.exists():
            with open(log_path, 'r') as f:
                lines = f.readlines()
                log_content = "".join(lines[-50:])
    except Exception as e:
        logging.error(f"Error reading log file: {e}", exc_info=True)
    return render_template('status.html', history=history, log_content=log_content, now=datetime.now())

@app.route('/history')
def history():
    return status()

@app.route('/sync', methods=['GET', 'POST'])
def sync():
    if request.method == 'POST':
        try:
            orchestrate_sync()
            return jsonify({'status': 'success', 'message': 'Sync triggered successfully'})
        except Exception as e:
            logging.error(f"Sync failed: {e}", exc_info=True)
            return jsonify({'status': 'error', 'message': str(e)}), 500
    return render_template('sync.html')

@app.route('/shelf/<shelf_name>')
def shelf_view(shelf_name):
    config = load_config()
    scraper = GoodreadsScraper(config)
    books = scraper.get_goodreads_books_from_shelf(shelf_name)
    sync_status = "Last sync: N/A"  # TODO: Pull from history or DB
    return render_template('shelf_view.html', books=books, shelf_name=shelf_name, sync_status=sync_status)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5002, debug=False)
EOF
mkdir -p "src/webui/templates"

echo "Creating file: src/webui/templates/layout.html"
cat << 'EOF' > "src/webui/templates/layout.html"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="60">
    <title>{% block title %}Ebooks Manager{% endblock %}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            margin: 0;
            padding: 2rem;
            background-color: #f4f7f6;
            color: #333;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background-color: #fff;
            padding: 2rem;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        h1, h2 {
            color: #2c3e50;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 0.5rem;
        }
        nav {
            margin-bottom: 1rem;
        }
        nav a {
            margin-right: 1rem;
            text-decoration: none;
            color: #2980b9;
        }
        nav a.active {
            font-weight: bold;
            color: #2c3e50;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 1rem;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
            vertical-align: top;
            word-break: break-word;
        }
        th {
            background-color: #f8f8f8;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #fdfdfd;
        }
        .status-success { color: #27ae60; font-weight: bold; }
        .status-failure { color: #c0392b; font-weight: bold; }
        .status-no_results { color: #f39c12; }
        .status-found { color: #2980b9; }
        pre {
            background-color: #2c3e50;
            color: #ecf0f1;
            padding: 1rem;
            border-radius: 4px;
            white-space: pre-wrap;
            word-wrap: break-word;
            max-height: 400px;
            overflow-y: auto;
        }
        .footer {
            margin-top: 2rem;
            text-align: center;
            font-size: 0.9em;
            color: #777;
        }
        code {
            background: #eee;
            padding: 2px 4px;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>{% block header %}Ebooks Manager{% endblock %}</h1>
        <nav>
            <a href="{{ url_for('status') }}" class="{{ 'active' if request.endpoint in ['status', 'index'] else '' }}">Status</a>
            <a href="{{ url_for('history') }}" class="{{ 'active' if request.endpoint == 'history' else '' }}">History</a>
            <a href="{{ url_for('sync') }}" class="{{ 'active' if request.endpoint == 'sync' else '' }}">Sync</a>
            <a href="{{ url_for('shelf_view', shelf_name='to-download') }}">To-Download Shelf</a>
        </nav>
        {% block content %}{% endblock %}
        <div class="footer">
            Ebooks Manager
        </div>
    </div>
</body>
</html>
EOF

echo "Creating file: src/webui/templates/sync.html"
cat << 'EOF' > "src/webui/templates/sync.html"
{% extends "layout.html" %}
{% block title %}Manual Sync{% endblock %}
{% block header %}Manual Sync{% endblock %}
{% block content %}
<p>Click to trigger sync:</p>
<form method="POST">
    <button type="submit">Run Sync Now</button>
</form>
{% endblock %}
EOF

echo "Creating file: src/webui/templates/status.html"
cat << 'EOF' > "src/webui/templates/status.html"
{% extends "layout.html" %}
{% block title %}Status{% endblock %}
{% block header %}Ebooks Manager Status{% endblock %}
{% block content %}
<p>This page automatically refreshes every 60 seconds. Last updated: {{ now | strftime }}</p>

<h2>Sync History (Newest First)</h2>
<table>
    <thead>
        <tr>
            <th style="width:15%">Timestamp</th>
            <th style="width:10%">Action</th>
            <th>Book Title / ID</th>
            <th>Details</th>
            <th style="width:10%">Status</th>
        </tr>
    </thead>
    <tbody>
        {% if history %}
            {% for entry in history %}
            <tr>
                <td>{{ entry.timestamp | strftime }}</td>
                <td><strong>{{ entry.action | capitalize }}</strong></td>
                <td>
                    <strong>{{ entry.title or 'N/A' }}</strong><br>
                    <small>ID: <code>{{ entry.book_id or '' }}</code></small>
                </td>
                <td>
                    {% if entry.query %}Query: <code>{{ entry.query }}</code><br>{% endif %}
                    {% if entry.result_id %}Result ID: <code>{{ entry.result_id }}</code>{% endif %}
                </td>
                <td>
                    {% if entry.status %}
                        <span class="status-{{ entry.status | lower }}">{{ entry.status | replace('_', ' ') | capitalize }}</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="5" style="text-align: center;">No history entries yet.</td>
            </tr>
        {% endif %}
    </tbody>
</table>

<h2>Recent Logs (Last 50 lines)</h2>
<pre><code>{{ log_content or 'Log file is empty or not found.' }}</code></pre>
{% endblock %}
EOF

echo "Creating file: src/webui/templates/shelf_view.html"
cat << 'EOF' > "src/webui/templates/shelf_view.html"
{% extends "layout.html" %}
{% block title %}{{ shelf_name | capitalize }} Shelf{% endblock %}
{% block header %}{{ shelf_name | capitalize }} Shelf (Sync Status: {{ sync_status }}){% endblock %}
{% block content %}
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Goodreads ID</th>
            <th>URL</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
            <td>{{ book.title }}</td>
            <td>{{ book.author }}</td>
            <td>{{ book.goodreads_id }}</td>
            <td><a href="{{ book.book_url }}">View</a></td>
        </tr>
        {% endfor %}
        {% if not books %}
        <tr><td colspan="4">No books found.</td></tr>
        {% endif %}
    </tbody>
</table>
{% endblock %}
EOF

echo "Creating file: src/webui/__init__.py"
cat << 'EOF' > "src/webui/__init__.py"
EOF
mkdir -p "src/utils"

echo "Creating file: src/utils/logger.py"
cat << 'EOF' > "src/utils/logger.py"
import logging
import sys
from pathlib import Path
import os

def setup_logger(log_file, level='INFO'):
    log_path = Path(log_file)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Ensure log file is writable
    log_path.touch(exist_ok=True)
    try:
        os.chmod(log_path, 0o664)
        os.chown(log_path, 1000, 1000)  # Match appuser UID/GID
    except PermissionError as e:
        print(f"Warning: Failed to set permissions on {log_path}: {e}")  # Fallback to print

    log_level = getattr(logging, level.upper(), logging.INFO)

    # Remove existing handlers to avoid duplicates
    for handler in logging.root.handlers[:]:
        logging.root.removeHandler(handler)

    # Create handlers
    file_handler = logging.FileHandler(log_path)
    file_handler.setLevel(log_level)
    file_handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    file_handler.flush()  # Ensure immediate flush

    stream_handler = logging.StreamHandler(sys.stdout)
    stream_handler.setLevel(log_level)
    stream_handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))

    # Configure root logger
    logging.basicConfig(
        level=log_level,
        handlers=[file_handler, stream_handler],
        force=True  # Force re-configuration
    )
    
    logging.getLogger("urllib3").setLevel(logging.WARNING)
    logging.getLogger("selenium").setLevel(logging.WARNING)
    
    logger = logging.getLogger()
    logger.debug(f"Logger initialized with file: {log_path}, level: {log_level}")
    return logger
EOF

echo "Creating file: src/utils/config_loader.py"
cat << 'EOF' > "src/utils/config_loader.py"
import json
import os
from pathlib import Path

def load_config(config_path='/app/config/config.json'):
    try:
        with open(config_path, 'r') as f:
            config = json.load(f)
        # Override with environment variables if set
        config['goodreads_username'] = os.getenv('GOODREADS_USERNAME', config.get('goodreads_username'))
        config['goodreads_password'] = os.getenv('GOODREADS_PASSWORD', config.get('goodreads_password'))
        config['goodreads_user_id'] = os.getenv('GOODREADS_USER_ID', config.get('goodreads_user_id'))
        config['cwa_api_url'] = os.getenv('CWA_API_URL', config.get('cwa_api_url'))
        config['cwa_username'] = os.getenv('CWA_USERNAME', config.get('cwa_username'))
        config['cwa_password'] = os.getenv('CWA_PASSWORD', config.get('cwa_password'))
        return config
    except FileNotFoundError:
        raise Exception(f"Configuration file {config_path} not found")
    except json.JSONDecodeError:
        raise Exception(f"Invalid JSON in configuration file {config_path}")
EOF

echo "Creating file: src/utils/database.py"
cat << 'EOF' > "src/utils/database.py"
import sqlite3
import json
from pathlib import Path

class Database:
    def __init__(self, db_path):
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self.init_db()

    def init_db(self):
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS books (
                    goodreads_id TEXT PRIMARY KEY,
                    title TEXT,
                    author TEXT,
                    series_name TEXT,
                    series_number TEXT,
                    pub_date TEXT,
                    num_pages INTEGER,
                    isbn TEXT,
                    asin TEXT,
                    language TEXT,
                    genres TEXT,
                    json_details TEXT
                )
            ''')
            conn.commit()

    def save_book(self, details):
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            json_details = json.dumps(details)
            cursor.execute('''
                INSERT OR REPLACE INTO books (goodreads_id, title, author, json_details)
                VALUES (?, ?, ?, ?)
            ''', (
                details['goodreads_id'],
                details.get('title'),
                details.get('author'),
                json_details
            ))
            conn.commit()
EOF

echo "Creating file: src/utils/__init__.py"
cat << 'EOF' > "src/utils/__init__.py"
EOF

echo "Creating file: src/job_runner.py"
cat << 'EOF' > "src/job_runner.py"
import logging
from apscheduler.schedulers.background import BackgroundScheduler
from src.sync_logic import orchestrate_sync
from src.utils.config_loader import load_config
from src.utils.logger import setup_logger
import os
import time

def run_jobs():
    logging.debug("Entering run_jobs function")
    # Prevent multiple scheduler instances
    if os.getenv('SCHEDULER_STARTED', 'false') == 'true':
        logging.info("Scheduler already running, skipping duplicate start.")
        return
    os.environ['SCHEDULER_STARTED'] = 'true'

    try:
        config = load_config()  # Load configuration
        logger = setup_logger(config['log_file'], os.getenv('LOG_LEVEL', 'DEBUG'))
        logging.info("Starting scheduler for daily sync.")
        scheduler = BackgroundScheduler()
        scheduler.add_job(orchestrate_sync, 'interval', hours=24)
        scheduler.start()
        logging.info("Scheduler started successfully")
        # Keep the container running
        while True:
            logging.debug("Scheduler loop running")
            time.sleep(3600)  # Sleep for an hour
    except Exception as e:
        logging.error(f"Scheduler failed: {str(e)}", exc_info=True)
        raise

if __name__ == "__main__":
    config = load_config()  # Load config early
    setup_logger(config['log_file'], os.getenv('LOG_LEVEL', 'DEBUG'))
    logging.info("Job runner starting")
    run_jobs()EOF

echo "Creating file: src/__init__.py"
cat << 'EOF' > "src/__init__.py"
EOF

echo "Creating file: docker-compose.yml"
cat << 'EOF' > "docker-compose.yml"
version: '3.8'
services:
  ebooks-manager:
    build:
      context: .
    container_name: ebooks-manager
    restart: unless-stopped
    env_file: /mnt/data/docker/docker-scripts/.env
    profiles:
      - "ebooks"
      - "mediaserver"
    labels:
      - "com.priority=24"
      - "homepage.group=Media Server"
      - "homepage.name=Book Manager"
      - "homepage.icon=download.svg"
      - "homepage.href=http://ebooks-manager.mayserver.local"
    depends_on:
      calibre-web:
        condition: service_healthy
      byparr-default:
        condition: service_healthy
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
      - FLARESOLVERR_URL=http://127.0.0.1:8191/v1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5002
      - LOG_LEVEL=DEBUG
      - DRY_RUN=no
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - WEBPAGE_CACHE_DAYS=30
    volumes:
      - /mnt/data/media/local/books/ingest:/cwa-book-ingest
      - /mnt/data/docker/docker-config/ebooks-manager/config:/app/config
      - /mnt/data/docker/docker-config/ebooks-manager/logs:/app/logs
      - /mnt/data/docker/docker-config/ebooks-manager/data:/app/data
    network_mode: "service:adguardhome_essential"
    shm_size: '4gb'
    ports:
      - "5002:5002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/status"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CAPTCHA_SOLVER=none
    ports:
      - "8191:8191"
    restart: unless-stopped
    network_mode: "service:adguardhome_essential"
EOF

echo "Creating file: README.md"
cat << 'EOF' > "README.md"
# Ebooks Manager

A Python-based project to manage ebook downloads by scraping Goodreads shelves using Selenium and interfacing with the Calibre-Web-Automated-Book-Downloader API.

## Setup

1. Copy `config/config.json.template` to `/mnt/data/docker/docker-config/ebooks-manager/config/config.json` or set environment variables (e.g., `GOODREADS_USERNAME`, `GOODREADS_PASSWORD`, `CWA_API_URL`, etc.) for credentials.
2. Copy `.env.example` to `.env` in the project root and adjust as needed.
3. Run `bash setup_project.sh` to create the project structure.
4. Run `docker-compose up --build` to build and start the containers (ebooks-manager and flaresolverr).
5. Access the web interface at `http://ebooks-manager.mayserver.local:5002`.

## Directory Structure

- `config/`: Configuration files
- `data/`: Databases, cache, and webpage storage
- `logs/`: History, sync logs, and screenshots
- `scripts/`: Entrypoint and setup scripts
- `src/`: Source code
  - `api/`: API clients (e.g., CWA)
  - `scrapers/`: Website scraping logic
  - `utils/`: Shared utilities
  - `webui/`: Web interface

## Environment Variables

- `GOODREADS_USERNAME`, `GOODREADS_PASSWORD`, `GOODREADS_USER_ID`: Goodreads credentials
- `CWA_API_URL`, `CWA_USERNAME`, `CWA_PASSWORD`: Calibre-Web API details
- `LOG_LEVEL`: Set to `DEBUG` for detailed logs and screenshots
- `DRY_RUN`: Set to `yes` to skip actual downloads
- `WEBPAGE_CACHE_DAYS`: Cache expiration in days (default: 30)
- `FLARESOLVERR_URL`: FlareSolverr service URL (default: `http://flaresolverr:8191/v1`)

## Debugging
- All screenshots are now full-page captures.
- If `LOG_LEVEL=DEBUG`, login failures trigger three rapid screenshots for diagnostics.
- Check `/status`, `/history`, `/shelf/to-download`, and `/sync` endpoints in the web UI.
EOF

echo "----------------------------------------------------"
echo "Project '$PROJECT_NAME' has been successfully created."
echo "You can now navigate into the new directory: cd '$PROJECT_NAME'"
echo "----------------------------------------------------"

